### ISSUE TITLE
Umiestnenie kamery

### ISSUE THREAD

**Issue by tbocinec** [TIS2016/Vrstevnice#10]
- [ ] Vytvoriť ikonku pre kameru

- [ ] Pridať možnosť pridania kamery na 2d mapu,

- [ ] Vymyslieť kde sa má zobraziť kamera keď nieje zvolená poloha uživaťeľom 

- [ ] Zmena kameri pomocou drag and drop

**Comment by iammatis** [comment]
Nakolko je drag and drop zlozity navrhujem to najprv spravit stylom "klik sem - klik tam"

**Comment by iammatis** [comment]
Pri nasadzovani sme narazili na mnozstvo problemov, z finalnej verzie zatial takisto skrtnute.

**Comment by iammatis** [comment]
Not Implemented
