### ISSUE TITLE
Neukoncené vrstevnice

### ISSUE THREAD

**Issue by tbocinec** [TIS2016/Vrstevnice#13]
Na začiatku sme stále odkladali problém z neukončenými  vrstevnicami ,mali by sme sa ku tomu vrátiť.

- V prvom rade by som navrhol opraviť tie  krivky ktoré sú len nedokreslené ale ďalej pokračujú.
![vystrizek](https://cloud.githubusercontent.com/assets/22387842/20641727/81295efc-b3fe-11e6-807f-ad06a876d37a.PNG)

**Comment by iammatis** [comment]
Jedno z možných riešení je toto nechať prerobiť v pozadí softvéru, čo však vytvára niekoľko komplikácií. Ďalšia varianta je časť takýchto vrstevníc odstrániť za pomoci vstupu od použivateľa a zvyšné dať dorobiť backendu.

**Comment by iammatis** [comment]
Vrstevnice Osetrene
