### ISSUE TITLE
testovacie scenáre

### ISSUE THREAD

**Issue by priebera1** [TIS2016/Vrstevnice#2]
tvorba scenárov

**Comment by priebera1** [comment]
Testovacie scenáre spravené
[Testovacie scenáre.pdf](https://github.com/TIS2016/Vrstevnice/files/607841/Testovacie.scenare.pdf)

**Comment by horvathova115** [comment]
testovacie scenáre : nieje to kompletné
	fungovanie približovania, rotácie
	prvé vety vyhodiť aj frázy ako v neposlednom rade
	testovať aj to čo sa nestihne naprogramovať
	príkazovy riadok - node
	- skôr vo forme bodov : urobí sa toto - stane sa toto /štrukturovaný text/

**Comment by iammatis** [comment]
- Vysledok testovania, samostatne priebeh testovania

**Comment by priebera1** [comment]
testovacie scenare upravene
- odstranene prve vety
- prerobene do bodov
- testovane aj to co sa nestihlo doprogramovat
