### ISSUE TITLE
Technická dokumentácia

### ISSUE THREAD

**Issue by horvathova115** [TIS2016/Vrstevnice#25]
takže technická dokumentácia obsahuje celú špecifikáciu, plus návrh a na záver sú tam pridané body ako spracovanie súboru a používanie aplikácie. 
Treba doplniť zmenené používateľské rozhranie,  triedny diagram, a používanie aplikácie s novým používateľským rozhraním.

[Technicka dokumentacia.docx](https://github.com/TIS2016/Vrstevnice/files/706981/Technicka.dokumentacia.docx)

**Comment by horvathova115** [comment]
prosím prečítajte si ju a pozrite to pouzivanie ci tam nieco nechyba a ci to je zrozumitelne.

**Comment by horvathova115** [comment]
upravila som pouzivanie aplikacie, ale stae mi tam nieco chyba, tak prosim sa na to este pozrite
Pouzivatelske rozhranie som dala take ake mame realne, este k nemu podopisujem cisla, aby sa dalo podla toho orientovt v tom pouzivani aplikacie.

[Technicka dokumentacia.docx](https://github.com/TIS2016/Vrstevnice/files/708997/Technicka.dokumentacia.docx)

**Comment by iammatis** [comment]
Upravit testovacie scenare podla najnovsej zapisnice z dna 16.01.2016

**Comment by horvathova115** [comment]
technicka dokumentacia skoro uplne hotova, chyba tam zhodnotenie algoritmov pouzitych  @iammatis  a popis k tridnemu diagramu @priebera1 
[Technicka dokumentacia.docx](https://github.com/TIS2016/Vrstevnice/files/778640/Technicka.dokumentacia.docx)

**Comment by priebera1** [comment]
technická dokumentácia dokončená
