### ISSUE TITLE
Používateľská príručka

### ISSUE THREAD

**Issue by iammatis** [TIS2016/Vrstevnice#33]
-pozuvivanie aplikacie - pouzivatelska prirucka - uvod, dva riadky

- popis ku "Stiahnutie mapy"

- ze musi dodať oramikované treba dopísať,
- treba tam napriklad aj to dopisat, ze pri vacsom rozostreni ci ako sa to vola, sa zvysuje mozno realna vykresovost alebo ako to nazvat no takisto sa nam zhorsuje kvalita alebo take nieco

**Comment by priebera1** [comment]
Používateľská príručka prepísaná
- pridaný popis ku Stiahnutiu mapy a návod na obsluhu aplikácie
