### ISSUE TITLE
Upravit vykreslovanie 3d mapy

### ISSUE THREAD

**Issue by iammatis** [TIS2016/Vrstevnice#7]
Upravit vykreslovanie za pomoci dostupnych prostriedkov v repozitary

**Comment by tbocinec** [comment]
Pre inšpiráciu si pozrite súbory v test-plugin.
Navrhujem najskôr spraviť iba pohybovanie a scroolovanie.

**Comment by iammatis** [comment]
- Stará 3D Mapa:
- [ ] Svetlo / Textura

- [ ] Pouzit mensi obrazok heightmapy

- Nová 3D Mapa:

- [x] Prepojit na canvas

- [x] Rozmery heightmapy orezat podla ohranicenie

- [x] Rozmery Obrazku na mensi obrazok

- [x] Spravne vykreslovanie
