### ISSUE TITLE
Ošetriť vstuspné súbory

### ISSUE THREAD

**Issue by tbocinec** [TIS2016/Vrstevnice#8]
Treba ošetriť vstupné subory.
Obmedzit na formáť,veľkosť.
Akú navrhujete maximalnu veľkost súboru ?

**Comment by iammatis** [comment]
Podla mna nam zatial netreba riesit velkost suborov, nechame to na neskor.

**Comment by priebera1** [comment]
idem osetrit formaty

**Comment by tbocinec** [comment]
už si ich ošetril ?

**Comment by iammatis** [comment]
Not Implemented
