### ISSUE TITLE
Textury

### ISSUE THREAD

**Issue by tbocinec** [TIS2016/Vrstevnice#9]
Vymyslieť-vytvoriť-nakresliť-doprogramovať-textury

- Textura okolia

- Textury podľa výšky kopca (zatiaľ nebolo pripravené pri programovaní)

Treba myslieť aj na umiestenie svetla.

**Comment by iammatis** [comment]
Textury sa stali prekazskou pri vykreslovani, vo finalnej verzii sa teda nachadzat asi nebudu.

**Comment by iammatis** [comment]
Not Implemented
